### ISSUE TITLE
add support for Pipfile

### ISSUE THREAD

**Issue by bobinson** [gitschwifty/pywit#7]
A better way to manage Python projects AFIK

A good read on this : https://jacobian.org/writing/python-environment-2018/

An essay: https://www.kennethreitz.org/essays/announcing-pipenv

**Comment by bobinson** [comment]
**Testing:**

**// clean**

(pywit)[11:08 PM] bobinson@air 🖖  [~/hack/pywit]pipenv clean
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (04fede)!
Uninstalling 'w3lib'…
Uninstalling 'voluptuous'…
Uninstalling 'virtualenv'…
Uninstalling 'virtualenv-clone'…
Uninstalling 'ujson'…
Uninstalling 'traitlets'…
Uninstalling 'tornado'…
Uninstalling 'toolz'…
Uninstalling 'tinman'…
Uninstalling 'testpath'…
Uninstalling 'steem'…
Uninstalling 'simplegeneric'…
Uninstalling 's3transfer'…
Uninstalling 'rsa'…
Uninstalling 'pyzmq'…
Uninstalling 'PyYAML'…
Uninstalling 'python-dateutil'…
Uninstalling 'Pygments'…
Uninstalling 'pycrypto'…
Uninstalling 'pyasn1'…
Uninstalling 'ptyprocess'…
Uninstalling 'prompt-toolkit'…
Uninstalling 'pipenv'…
Uninstalling 'pickleshare'…
Uninstalling 'pexpect'…
Uninstalling 'parso'…
Uninstalling 'numpy'…
Uninstalling 'nose'…
Uninstalling 'nbformat'…
Uninstalling 'MarkupSafe'…
Uninstalling 'langdetect'…
Uninstalling 'jupyter-core'…
Uninstalling 'jupyter-client'…
Uninstalling 'jsonschema'…
Uninstalling 'jmespath'…
Uninstalling 'Jinja2'…
Uninstalling 'jedi'…
Uninstalling 'ipython'…
Uninstalling 'ipython-genutils'…
Uninstalling 'ipykernel'…
Uninstalling 'ijson'…
Uninstalling 'funcy'…
Uninstalling 'ff'…
Uninstalling 'docutils'…
Uninstalling 'decorator'…
Uninstalling 'Click'…
Uninstalling 'botocore'…
Uninstalling 'backcall'…
Uninstalling 'awscli'…
Uninstalling 'appnope'…
Uninstalling 'conductor'…
Uninstalling 'tabulate'…
Uninstalling 'pywit'…
Uninstalling 'Events'…


**// generating Pipfile.lock**
(pywit)[11:11 PM] bobinson@air 🖖  [~/hack/pywit]pipenv lock
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (04fede)!

**// Installing **

1. While in progress
(pywit)[11:12 PM] bobinson@air 🖖  [~/hack/pywit]pipenv  install
Installing dependencies from Pipfile.lock (04fede)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 15/50 — 00:


2. completed

(pywit)[11:12 PM] bobinson@air 🖖  [~/hack/pywit]pipenv  install
Installing dependencies from Pipfile.lock (04fede)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 50/50 — 0



**// pip install **


[11:14 PM] bobinson@air 🖖  [~/hack/pywit]pip install .

  Running setup.py install for pywit ... done
Successfully installed pywit-1.1.0
[11:14 PM] bobinson@air 🖖  [~/hack/pywit]


**// pip uninstall **


[11:14 PM] bobinson@air 🖖  [~/hack/pywit]pip uninstall pywit
Uninstalling pywit-1.1.0:
  Would remove:
    /Users/b5413b/.pyenv/versions/3.6.5/bin/pywit
    /Users/b5413b/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pywit-1.1.0-py3.6.egg-info
    /Users/b5413b/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pywit/*
    /Users/b5413b/.pyenv/versions/3.6.5/lib/python3.6/site-packages/testing/*

Proceed (y/n)? y
  Successfully uninstalled pywit-1.1.0

**Comment by gitschwifty** [comment]
Merged from pull request #8, thanks for the help on this! I'd looked at pipfiles but the documentation I'd found was not too helpful.
