### ISSUE TITLE
PEP-8 coding style will be good

### ISSUE THREAD

**Issue by bobinson** [gitschwifty/pywit#9]
Adopting PEP-8 coding style will be a welcome thing for the code base. An answer as to why is here https://github.com/steemit/tinman/issues/171

Further, PyCharm is an editor which has inbuilt support for many nice features including PEP-8 suggestions

**Comment by gitschwifty** [comment]
I used autopep8 in Atom to start with it and looked through for obvious errors, will be attempting to complete PEP8 compliance this week and continue to maintain it.
